import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import ReduxProviders from "@/store/ReduxProvider";
import Footer from "@/components/layout/Footer";
import ProgressBarProviders from "@/components/miniWidgets/ProgressBar";
import { ToastContainer } from "react-toastify";
import Booking from "@/components/miniWidgets/Wrapper";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Restaurant Website",
  description: "Generated by create next app",
};
const NEXT_PUBLIC_BASE_URL = "https://yummy-yatch.netlify.app/";

const fetchData = async () => {
  try {
    const menuResponse = await fetch(`${NEXT_PUBLIC_BASE_URL}/data/menu.json`);
    const menuData = await menuResponse.json();
    // console.log("menu in layout", menuData);

    const eventResponse = await fetch(
      `${NEXT_PUBLIC_BASE_URL}/data/venues.json`
    );
    const eventData = await eventResponse.json();
    // console.log("evnets in layout", eventData);

    return { menuData, eventData };
  } catch (error) {
    console.error("Error fetching data:", error);
    return { menuData: null, eventData: null };
  }
};

export default async function RootLayout({ children }) {
  const { menuData, eventData } = await fetchData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ReduxProviders menuData={menuData} eventData={eventData}>
          <main className="w-full box-border overflow-hidden">
            <ProgressBarProviders>
              <Booking />
              <Navbar />
              {children}
              <Footer />
            </ProgressBarProviders>
            <ToastContainer />
          </main>
        </ReduxProviders>
      </body>
    </html>
  );
}
